from __future__ import annotations

from datetime import date


def quant_dashboard() -> dict:
    today = date.today().isoformat()
    return {
        "generated_at": f"{today}T15:30:00+08:00",
        "service_mode": "sample",
        "market": {
            "trade_date": today,
            "temperature": 63,
            "up_count": 3128,
            "down_count": 1934,
            "flat_count": 217,
            "turnover_billion": 948.6,
            "indices": [
                {
                    "code": "000001.SH",
                    "name": "上证指数",
                    "price": 3421.18,
                    "change_pct": 0.42,
                    "turnover_billion": 412.3,
                },
                {
                    "code": "399001.SZ",
                    "name": "深证成指",
                    "price": 10884.62,
                    "change_pct": 0.68,
                    "turnover_billion": 536.3,
                },
                {
                    "code": "399006.SZ",
                    "name": "创业板指",
                    "price": 2216.74,
                    "change_pct": -0.11,
                    "turnover_billion": 214.8,
                },
                {
                    "code": "000300.SH",
                    "name": "沪深300",
                    "price": 3978.45,
                    "change_pct": 0.35,
                    "turnover_billion": 286.5,
                },
            ],
            "sectors": [
                {"name": "半导体", "change_pct": 2.34, "signal": "volume_breakout"},
                {"name": "电力设备", "change_pct": 1.42, "signal": "trend_recovery"},
                {"name": "银行", "change_pct": 0.58, "signal": "defensive"},
                {"name": "传媒", "change_pct": -1.21, "signal": "risk_off"},
            ],
        },
        "watchlist": [
            {
                "code": "600519.SH",
                "name": "贵州茅台",
                "price": 1478.2,
                "change_pct": 0.31,
                "turnover_billion": 4.8,
                "pe_ttm": 24.6,
                "roe": 31.2,
                "tags": ["核心资产", "低波动"],
            },
            {
                "code": "300750.SZ",
                "name": "宁德时代",
                "price": 213.64,
                "change_pct": 1.84,
                "turnover_billion": 9.2,
                "pe_ttm": 19.8,
                "roe": 20.5,
                "tags": ["新能源", "趋势修复"],
            },
            {
                "code": "601318.SH",
                "name": "中国平安",
                "price": 48.91,
                "change_pct": -0.24,
                "turnover_billion": 3.1,
                "pe_ttm": 8.7,
                "roe": 12.4,
                "tags": ["低估值", "金融"],
            },
            {
                "code": "688981.SH",
                "name": "中芯国际",
                "price": 58.33,
                "change_pct": 3.12,
                "turnover_billion": 12.6,
                "pe_ttm": 78.4,
                "roe": 5.8,
                "tags": ["半导体", "放量"],
            },
        ],
        "signals": [
            {
                "id": "sig-20260720-001",
                "strategy": "20日均线突破",
                "code": "688981.SH",
                "name": "中芯国际",
                "action": "observe",
                "strength": 82,
                "reason": "收盘价站上20日均线且成交额放大至近20日均值的1.8倍。",
                "risk": "估值较高，适合观察或轻仓验证。",
            },
            {
                "id": "sig-20260720-002",
                "strategy": "低估值高ROE",
                "code": "601318.SH",
                "name": "中国平安",
                "action": "watch",
                "strength": 67,
                "reason": "PE处于历史偏低分位，ROE保持稳定。",
                "risk": "金融板块弹性较弱，需关注指数环境。",
            },
            {
                "id": "sig-20260720-003",
                "strategy": "趋势修复",
                "code": "300750.SZ",
                "name": "宁德时代",
                "action": "buy_candidate",
                "strength": 74,
                "reason": "价格重新回到60日均线上方，行业热度回升。",
                "risk": "新能源板块波动较大，建议设置仓位上限。",
            },
        ],
        "portfolio": {
            "mode": "paper",
            "total_value": 258430.75,
            "cash": 68420.25,
            "daily_pnl": 1842.4,
            "daily_pnl_pct": 0.72,
            "total_pnl": 18430.75,
            "total_pnl_pct": 7.67,
            "max_drawdown_pct": -5.8,
            "positions": [
                {
                    "code": "600519.SH",
                    "name": "贵州茅台",
                    "quantity": 40,
                    "cost": 1432.5,
                    "price": 1478.2,
                    "market_value": 59128.0,
                    "pnl_pct": 3.19,
                    "weight_pct": 22.88,
                },
                {
                    "code": "300750.SZ",
                    "name": "宁德时代",
                    "quantity": 500,
                    "cost": 205.1,
                    "price": 213.64,
                    "market_value": 106820.0,
                    "pnl_pct": 4.16,
                    "weight_pct": 41.33,
                },
                {
                    "code": "601318.SH",
                    "name": "中国平安",
                    "quantity": 500,
                    "cost": 50.2,
                    "price": 48.91,
                    "market_value": 24455.0,
                    "pnl_pct": -2.57,
                    "weight_pct": 9.46,
                },
            ],
            "risk": {
                "cash_weight_pct": 26.48,
                "largest_position_pct": 41.33,
                "sector_concentration": "新能源 41.33%",
                "alerts": [
                    "单一持仓宁德时代超过40%，建议检查仓位上限。",
                    "组合处于模拟模式，尚未连接实盘交易网关。",
                ],
            },
        },
        "daily_report": {
            "title": "A股盘后复盘",
            "summary": "市场温度偏暖，成交额接近万亿。半导体和电力设备相对强势，传媒回调。当前组合日内跑赢沪深300，主要贡献来自宁德时代和中芯国际观察信号。",
            "next_actions": [
                "明日重点观察半导体放量后的持续性。",
                "检查宁德时代仓位是否超过个人风控阈值。",
                "对低估值金融策略保持观察，不急于提高仓位。",
            ],
        },
    }
