import type { AgentToolDescriptor, AgentToolRuntime } from "./types";

const CHAT_AND_LOOP: AgentToolRuntime[] = ["chat", "loop"];
const ALL_AGENT_RUNTIMES: AgentToolRuntime[] = [
  "chat",
  "workshop",
  "loop",
  "cron",
];

export const CLAUDE_BUILTIN_TOOLS: AgentToolDescriptor[] = [
  {
    id: "claude:Read",
    name: "Read",
    displayName: "Read",
    source: "claude_builtin",
    description: "Read files from the agent working directory.",
    capabilities: ["file_read"],
    risk: "medium",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:Edit",
    name: "Edit",
    displayName: "Edit",
    source: "claude_builtin",
    description: "Edit existing files in the agent working directory.",
    capabilities: ["file_write"],
    risk: "high",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:Write",
    name: "Write",
    displayName: "Write",
    source: "claude_builtin",
    description: "Create or overwrite files in the agent working directory.",
    capabilities: ["file_write"],
    risk: "high",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:Glob",
    name: "Glob",
    displayName: "Glob",
    source: "claude_builtin",
    description: "Find files by path pattern.",
    capabilities: ["file_read"],
    risk: "low",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:Grep",
    name: "Grep",
    displayName: "Grep",
    source: "claude_builtin",
    description: "Search local file contents.",
    capabilities: ["file_read"],
    risk: "low",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:Bash",
    name: "Bash",
    displayName: "Bash",
    source: "claude_builtin",
    description: "Run shell commands in the agent working directory.",
    capabilities: ["code_exec", "file_read", "file_write"],
    risk: "critical",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:WebSearch",
    name: "WebSearch",
    displayName: "WebSearch",
    source: "claude_builtin",
    description: "Search the web for current information.",
    capabilities: ["web_read"],
    risk: "medium",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:WebFetch",
    name: "WebFetch",
    displayName: "WebFetch",
    source: "claude_builtin",
    description: "Fetch and read web pages.",
    capabilities: ["web_read"],
    risk: "medium",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:Skill",
    name: "Skill",
    displayName: "Skill",
    source: "claude_builtin",
    description: "Invoke installed local skills.",
    capabilities: ["unknown"],
    risk: "medium",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:Task",
    name: "Task",
    displayName: "Task",
    source: "claude_builtin",
    description: "Run a sub-agent task.",
    capabilities: ["unknown"],
    risk: "medium",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:LSP",
    name: "LSP",
    displayName: "LSP",
    source: "claude_builtin",
    description: "Inspect code with language server features.",
    capabilities: ["file_read"],
    risk: "low",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
  {
    id: "claude:TodoWrite",
    name: "TodoWrite",
    displayName: "TodoWrite",
    source: "claude_builtin",
    description: "Track agent task progress.",
    capabilities: ["unknown"],
    risk: "low",
    runtimeScopes: ["chat", "workshop", "loop"],
  },
];

export const BUSINESS_TOOLS: AgentToolDescriptor[] = [
  {
    id: "business:time",
    name: "time",
    displayName: "time",
    source: "business_tools",
    serverName: "business-tools",
    description: "Read current time and timezone context.",
    capabilities: ["time"],
    risk: "low",
    runtimeScopes: ["chat", "workshop", "loop", "cron"],
  },
  {
    id: "business:chatInsight",
    name: "chatInsight",
    displayName: "chatInsight",
    source: "business_tools",
    serverName: "business-tools",
    description: "Query insight context for the current chat.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: CHAT_AND_LOOP,
  },
  {
    id: "business:downloadInsightAttachment",
    name: "downloadInsightAttachment",
    displayName: "downloadInsightAttachment",
    source: "business_tools",
    serverName: "business-tools",
    description: "Download an attachment associated with an insight.",
    capabilities: ["knowledge_read", "file_write"],
    risk: "medium",
    runtimeScopes: CHAT_AND_LOOP,
  },
  {
    id: "business:queryContacts",
    name: "queryContacts",
    displayName: "queryContacts",
    source: "business_tools",
    serverName: "business-tools",
    description: "Query known contacts from connected integrations.",
    capabilities: ["message_read"],
    risk: "medium",
    runtimeScopes: CHAT_AND_LOOP,
  },
  {
    id: "business:queryIntegrations",
    name: "queryIntegrations",
    displayName: "queryIntegrations",
    source: "business_tools",
    serverName: "business-tools",
    description: "Inspect connected integration availability.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: CHAT_AND_LOOP,
  },
  {
    id: "business:sendReply",
    name: "sendReply",
    displayName: "sendReply",
    source: "business_tools",
    serverName: "business-tools",
    description: "Send a reply through the current conversation channel.",
    capabilities: ["external_send"],
    risk: "critical",
    runtimeScopes: CHAT_AND_LOOP,
  },
  {
    id: "business:createInsight",
    name: "createInsight",
    displayName: "createInsight",
    source: "business_tools",
    serverName: "business-tools",
    description: "Create a persisted insight.",
    capabilities: ["knowledge_read", "memory_write"],
    risk: "medium",
    runtimeScopes: CHAT_AND_LOOP,
  },
  {
    id: "business:modifyInsight",
    name: "modifyInsight",
    displayName: "modifyInsight",
    source: "business_tools",
    serverName: "business-tools",
    description: "Modify an existing insight.",
    capabilities: ["memory_write"],
    risk: "medium",
    runtimeScopes: CHAT_AND_LOOP,
  },
  {
    id: "business:deleteInsight",
    name: "deleteInsight",
    displayName: "deleteInsight",
    source: "business_tools",
    serverName: "business-tools",
    description: "Delete an existing insight.",
    capabilities: ["memory_write"],
    risk: "high",
    runtimeScopes: CHAT_AND_LOOP,
  },
  {
    id: "business:searchKnowledgeBase",
    name: "searchKnowledgeBase",
    displayName: "searchKnowledgeBase",
    source: "business_tools",
    serverName: "business-tools",
    description: "Search the knowledge base.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ["chat", "workshop", "loop", "cron"],
  },
  {
    id: "business:getFullDocumentContent",
    name: "getFullDocumentContent",
    displayName: "getFullDocumentContent",
    source: "business_tools",
    serverName: "business-tools",
    description: "Read a full knowledge-base document.",
    capabilities: ["knowledge_read", "document"],
    risk: "low",
    runtimeScopes: ["chat", "workshop", "loop", "cron"],
  },
  {
    id: "business:listKnowledgeBaseDocuments",
    name: "listKnowledgeBaseDocuments",
    displayName: "listKnowledgeBaseDocuments",
    source: "business_tools",
    serverName: "business-tools",
    description: "List available knowledge-base documents.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ["chat", "workshop", "loop", "cron"],
  },
  {
    id: "business:searchUnifiedMemory",
    name: "searchUnifiedMemory",
    displayName: "searchUnifiedMemory",
    source: "business_tools",
    serverName: "business-tools",
    description: "Search unified long-term memory.",
    capabilities: ["memory_read"],
    risk: "medium",
    runtimeScopes: ["chat", "workshop", "loop", "cron"],
  },
  {
    id: "business:searchMemoryPath",
    name: "searchMemoryPath",
    displayName: "searchMemoryPath",
    source: "business_tools",
    serverName: "business-tools",
    description: "Search a specific memory path.",
    capabilities: ["memory_read"],
    risk: "medium",
    runtimeScopes: ["chat", "workshop", "loop", "cron"],
  },
  {
    id: "business:getRawMessages",
    name: "getRawMessages",
    displayName: "getRawMessages",
    source: "business_tools",
    serverName: "business-tools",
    description: "Read raw connected-channel messages.",
    capabilities: ["message_read"],
    risk: "high",
    runtimeScopes: ["chat", "workshop", "loop", "cron"],
  },
  {
    id: "business:searchRawMessages",
    name: "searchRawMessages",
    displayName: "searchRawMessages",
    source: "business_tools",
    serverName: "business-tools",
    description: "Search raw connected-channel messages.",
    capabilities: ["message_read"],
    risk: "high",
    runtimeScopes: ["chat", "workshop", "loop", "cron"],
  },
  {
    id: "business:createLoopTask",
    name: "createLoopTask",
    displayName: "createLoopTask",
    source: "business_tools",
    serverName: "business-tools",
    description: "Create a durable recurring or scheduled automation task.",
    capabilities: ["task_create"],
    risk: "high",
    runtimeScopes: ["chat", "loop"],
  },
  {
    id: "business:inspectWorkshopAgent",
    name: "inspectWorkshopAgent",
    displayName: "inspectWorkshopAgent",
    source: "business_tools",
    serverName: "business-tools",
    description:
      "Inspect workshop agent configuration before proposing changes.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ["chat"],
  },
  {
    id: "business:proposeWorkshopAgentChange",
    name: "proposeWorkshopAgentChange",
    displayName: "proposeWorkshopAgentChange",
    source: "business_tools",
    serverName: "business-tools",
    description:
      "Create an owner-reviewable proposal to change a workshop agent configuration.",
    capabilities: ["memory_write"],
    risk: "high",
    runtimeScopes: ["chat"],
  },
  {
    id: "business:listWorkshopManifestCapabilities",
    name: "listWorkshopManifestCapabilities",
    displayName: "listWorkshopManifestCapabilities",
    source: "business_tools",
    serverName: "business-tools",
    description:
      "List tools and skills that can be referenced by a Workshop YAML manifest.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ["chat"],
  },
  {
    id: "business:reviewWorkshopManifestYaml",
    name: "reviewWorkshopManifestYaml",
    displayName: "reviewWorkshopManifestYaml",
    source: "business_tools",
    serverName: "business-tools",
    description:
      "Dry-run review a Workshop YAML manifest without creating anything.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ["chat"],
  },
  {
    id: "business:applyWorkshopManifestYaml",
    name: "applyWorkshopManifestYaml",
    displayName: "applyWorkshopManifestYaml",
    source: "business_tools",
    serverName: "business-tools",
    description:
      "Create a Workshop from a reviewed YAML manifest after explicit user confirmation.",
    capabilities: ["task_create", "memory_write"],
    risk: "high",
    runtimeScopes: ["chat"],
  },
  {
    id: "business:listLoopTasks",
    name: "listLoopTasks",
    displayName: "listLoopTasks",
    source: "business_tools",
    serverName: "business-tools",
    description: "List durable automation tasks.",
    capabilities: ["task_manage"],
    risk: "medium",
    runtimeScopes: ["chat", "loop"],
  },
  {
    id: "business:setLoopTaskStatus",
    name: "setLoopTaskStatus",
    displayName: "setLoopTaskStatus",
    source: "business_tools",
    serverName: "business-tools",
    description: "Pause, resume, or update automation task status.",
    capabilities: ["task_manage"],
    risk: "high",
    runtimeScopes: ["chat", "loop"],
  },
  {
    id: "business:updateLoopTask",
    name: "updateLoopTask",
    displayName: "updateLoopTask",
    source: "business_tools",
    serverName: "business-tools",
    description:
      "Modify an existing automation task in place without deleting it.",
    capabilities: ["task_manage"],
    risk: "high",
    runtimeScopes: ["chat"],
  },
  {
    id: "business:deleteLoopTask",
    name: "deleteLoopTask",
    displayName: "deleteLoopTask",
    source: "business_tools",
    serverName: "business-tools",
    description: "Delete an automation task.",
    capabilities: ["task_manage"],
    risk: "high",
    runtimeScopes: ["chat", "loop"],
  },
  {
    id: "business:wechatDesktopHealth",
    name: "wechatDesktopHealth",
    displayName: "wechatDesktopHealth",
    source: "business_tools",
    serverName: "business-tools",
    description: "Check local Windows WeChat desktop bridge health.",
    capabilities: ["message_read"],
    risk: "medium",
    runtimeScopes: ["chat", "loop"],
  },
  {
    id: "business:wechatDesktopPreviewMessage",
    name: "wechatDesktopPreviewMessage",
    displayName: "wechatDesktopPreviewMessage",
    source: "business_tools",
    serverName: "business-tools",
    description: "Create a local WeChat message preview.",
    capabilities: ["external_draft"],
    risk: "high",
    runtimeScopes: ["chat"],
  },
  {
    id: "business:wechatDesktopSendMessage",
    name: "wechatDesktopSendMessage",
    displayName: "wechatDesktopSendMessage",
    source: "business_tools",
    serverName: "business-tools",
    description: "Send a message through local Windows WeChat desktop.",
    capabilities: ["external_send"],
    risk: "critical",
    runtimeScopes: ["loop"],
  },
];

export const WORKSHOP_TOOLS: AgentToolDescriptor[] = [
  {
    id: "workshop:workshopLogEvent",
    name: "workshopLogEvent",
    displayName: "workshopLogEvent",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Append a workshop event.",
    capabilities: ["memory_write"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopInspectWork",
    name: "workshopInspectWork",
    displayName: "workshopInspectWork",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Inspect the current Workshop Work model, tool matrix, events, and versions.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopProposeAgentChange",
    name: "workshopProposeAgentChange",
    displayName: "workshopProposeAgentChange",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Create an owner-reviewable proposal to change the current Workshop Work configuration.",
    capabilities: ["memory_write"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:webReadPage",
    name: "webReadPage",
    displayName: "webReadPage",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Read a public web page with workshop source handling.",
    capabilities: ["web_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopListSources",
    name: "workshopListSources",
    displayName: "workshopListSources",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "List workshop sources.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopGetDirectives",
    name: "workshopGetDirectives",
    displayName: "workshopGetDirectives",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Read active workshop directives.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopReadMemory",
    name: "workshopReadMemory",
    displayName: "workshopReadMemory",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Read workshop memory.",
    capabilities: ["memory_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopSearchMemory",
    name: "workshopSearchMemory",
    displayName: "workshopSearchMemory",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Search workshop memory by task intent and return a control context pack.",
    capabilities: ["memory_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopRecordMemoryRecallFeedback",
    name: "workshopRecordMemoryRecallFeedback",
    displayName: "workshopRecordMemoryRecallFeedback",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Append structured recall-quality feedback without changing memory or policy.",
    capabilities: ["memory_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopInspectMemoryRecallQuality",
    name: "workshopInspectMemoryRecallQuality",
    displayName: "workshopInspectMemoryRecallQuality",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Inspect aggregate recall telemetry for a dedicated memory quality Work.",
    capabilities: ["memory_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopInspectHarnessQuality",
    name: "workshopInspectHarnessQuality",
    displayName: "workshopInspectHarnessQuality",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "List owned Harness targets or inspect desensitized snapshots, run evidence, diagnostics, proposals, and evaluation status for one Work.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopCreateHarnessProposal",
    name: "workshopCreateHarnessProposal",
    displayName: "workshopCreateHarnessProposal",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Create a complete owner-reviewable Harness Change Proposal v2 for another owned Work without applying it.",
    capabilities: ["memory_write"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopCreateHarnessEvaluationCampaign",
    name: "workshopCreateHarnessEvaluationCampaign",
    displayName: "workshopCreateHarnessEvaluationCampaign",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Create an isolated baseline-versus-candidate Harness evaluation campaign after owner approval.",
    capabilities: ["task_create", "knowledge_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopRunHarnessEvaluation",
    name: "workshopRunHarnessEvaluation",
    displayName: "workshopRunHarnessEvaluation",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Run a bounded deterministic Harness evaluation in an environment with external, destructive, and real-funds actions disabled.",
    capabilities: ["task_manage", "knowledge_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopGetMemoryEvidence",
    name: "workshopGetMemoryEvidence",
    displayName: "workshopGetMemoryEvidence",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Expand a workshop memory into its supporting evidence events.",
    capabilities: ["memory_read", "knowledge_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopReadLinkedWorkshopEvents",
    name: "workshopReadLinkedWorkshopEvents",
    displayName: "workshopReadLinkedWorkshopEvents",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Read recent events from workshops linked to the current workshop.",
    capabilities: ["knowledge_read", "memory_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopListMemoryCandidates",
    name: "workshopListMemoryCandidates",
    displayName: "workshopListMemoryCandidates",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "List workshop memory candidates awaiting stewardship.",
    capabilities: ["memory_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopReviewMemory",
    name: "workshopReviewMemory",
    displayName: "workshopReviewMemory",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Activate, verify, weaken, or dismiss workshop memory after evidence or outcome review.",
    capabilities: ["memory_write"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopWriteMemory",
    name: "workshopWriteMemory",
    displayName: "workshopWriteMemory",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Write workshop memory.",
    capabilities: ["memory_write"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopCreateLoopTask",
    name: "workshopCreateLoopTask",
    displayName: "workshopCreateLoopTask",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Create a paused loop proposal from a workshop.",
    capabilities: ["task_create"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:aStockQuote",
    name: "aStockQuote",
    displayName: "读取 A 股行情",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Fetch A-share quote data.",
    capabilities: ["market_data", "web_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:aStockResearch",
    name: "aStockResearch",
    displayName: "读取投研数据",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Fetch A-share research and summaries.",
    capabilities: ["market_data", "web_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:aStockSignals",
    name: "aStockSignals",
    displayName: "读取资金/信号",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Generate A-share signal candidates.",
    capabilities: ["market_data"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:aStockTrend",
    name: "aStockTrend",
    displayName: "读取趋势结构",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Fetch daily K-line trend structure, MA/ATR stops, and trend score.",
    capabilities: ["market_data"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:aStockTrendSystem",
    name: "aStockTrendSystem",
    displayName: "读取趋势跟随系统",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Build watchlist-level trend state, relative-strength ranking, stop plan, and strategy statistics.",
    capabilities: ["market_data"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:aStockTrendStateHistory",
    name: "aStockTrendStateHistory",
    displayName: "读取趋势状态历史",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Read persisted trend-following state snapshots for replay, deterioration checks, and strategy statistics.",
    capabilities: ["market_data", "memory_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:aStockTrendStrategyStats",
    name: "aStockTrendStrategyStats",
    displayName: "读取趋势策略样本",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Evaluate persisted trend state samples against the paper account and summarize outcome statistics by lifecycle state.",
    capabilities: ["market_data", "memory_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:aStockFundamentals",
    name: "aStockFundamentals",
    displayName: "读取基本面",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Fetch A-share fundamentals.",
    capabilities: ["market_data", "web_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:aStockNewsAndFilings",
    name: "aStockNewsAndFilings",
    displayName: "读取新闻公告",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Fetch A-share news and filings.",
    capabilities: ["market_data", "web_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:aStockMarketMood",
    name: "aStockMarketMood",
    displayName: "读取市场情绪",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Summarize A-share market mood.",
    capabilities: ["market_data", "web_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:quantPaperGetAccount",
    name: "quantPaperGetAccount",
    displayName: "quantPaperGetAccount",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Read the paper-trading account, positions, open orders, and fills.",
    capabilities: ["market_data"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:quantTradePlanList",
    name: "quantTradePlanList",
    displayName: "Read trade plan ledger",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Read durable paper-trading plans, execution status, blockers, and due dates.",
    capabilities: ["market_data", "memory_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:quantTradePlanUpsert",
    name: "quantTradePlanUpsert",
    displayName: "Write trade plan",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Persist or revise paper-trading plans with trigger, invalidation, rationale, and due date.",
    capabilities: ["market_data", "task_manage"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:quantTradePlanReview",
    name: "quantTradePlanReview",
    displayName: "Review trade plan",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Update plan execution status with order id, blocker reason, or completion note.",
    capabilities: ["market_data", "task_manage"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:quantRuleEvaluate",
    name: "quantRuleEvaluate",
    displayName: "Evaluate numeric trading rules",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Deterministically evaluate numeric trading, stop, trigger, invalidation, cash, and position rules in batches.",
    capabilities: ["market_data"],
    risk: "low",
    runtimeScopes: ["workshop", "loop"],
  },
  {
    id: "workshop:watchlistFollowupTaskUpsert",
    name: "watchlistFollowupTaskUpsert",
    displayName: "watchlistFollowupTaskUpsert",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Persist or update structured follow-up tasks for watchlist candidates and blockers.",
    capabilities: ["market_data", "task_manage"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:watchlistFollowupTaskList",
    name: "watchlistFollowupTaskList",
    displayName: "watchlistFollowupTaskList",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Read structured watchlist follow-up tasks carried from previous loops.",
    capabilities: ["market_data", "task_manage"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:watchlistCandidateAgeReview",
    name: "watchlistCandidateAgeReview",
    displayName: "watchlistCandidateAgeReview",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Review candidate age, stale candidates, repeated blockers, and protected symbols.",
    capabilities: ["market_data"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:watchlistChangeHistory",
    name: "watchlistChangeHistory",
    displayName: "watchlistChangeHistory",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Read auditable watchlist proposal, discovery, and follow-up history.",
    capabilities: ["market_data"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:watchlistPerformanceReview",
    name: "watchlistPerformanceReview",
    displayName: "watchlistPerformanceReview",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Review current quote performance for watchlist and candidate symbols.",
    capabilities: ["market_data"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:quantMarketDiscoverCandidates",
    name: "quantMarketDiscoverCandidates",
    displayName: "quantMarketDiscoverCandidates",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Discover reliable A-share market candidates for watchlist review.",
    capabilities: ["market_data", "web_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:quantPaperGetWatchlist",
    name: "quantPaperGetWatchlist",
    displayName: "quantPaperGetWatchlist",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Read the paper-trading watchlist with current quote snapshots.",
    capabilities: ["market_data"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:quantPaperProposeWatchlistChange",
    name: "quantPaperProposeWatchlistChange",
    displayName: "quantPaperProposeWatchlistChange",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Create an auditable watchlist-change proposal and auto-apply it when validation passes.",
    capabilities: ["market_data", "task_manage"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:quantPaperPlaceOrder",
    name: "quantPaperPlaceOrder",
    displayName: "quantPaperPlaceOrder",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Submit a simulated paper-trading limit order.",
    capabilities: ["market_data"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:quantPaperCancelOrder",
    name: "quantPaperCancelOrder",
    displayName: "quantPaperCancelOrder",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Cancel a simulated paper-trading order.",
    capabilities: ["market_data"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:wechatLocalHealth",
    name: "wechatLocalHealth",
    displayName: "wechatLocalHealth",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Check local WeChat read bridge health.",
    capabilities: ["message_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:wechatRecordNewMessages",
    name: "wechatRecordNewMessages",
    displayName: "wechatRecordNewMessages",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Read new local WeChat messages and persist them as Owner Context evidence.",
    capabilities: ["message_read", "memory_write"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:wechatListRecordedMessages",
    name: "wechatListRecordedMessages",
    displayName: "wechatListRecordedMessages",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "List persisted WeChat interaction events.",
    capabilities: ["message_read", "memory_read"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:wechatMarkMessagesProcessed",
    name: "wechatMarkMessagesProcessed",
    displayName: "wechatMarkMessagesProcessed",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Update processing status for persisted WeChat interaction events.",
    capabilities: ["memory_write"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:interactionCreateWikiNote",
    name: "interactionCreateWikiNote",
    displayName: "interactionCreateWikiNote",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Create a traceable interaction wiki note from recorded messages.",
    capabilities: ["memory_write", "message_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:interactionProcessRecordedMessages",
    name: "interactionProcessRecordedMessages",
    displayName: "interactionProcessRecordedMessages",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Run the interaction understanding processor for recorded message events.",
    capabilities: ["message_read", "memory_write", "task_create"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:interactionCreateTaskCandidate",
    name: "interactionCreateTaskCandidate",
    displayName: "interactionCreateTaskCandidate",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Create a task candidate extracted from recorded interaction events.",
    capabilities: ["task_create", "memory_write"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:interactionCreateMemoryCandidate",
    name: "interactionCreateMemoryCandidate",
    displayName: "interactionCreateMemoryCandidate",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Create a long-term Owner Context candidate with source evidence.",
    capabilities: ["memory_write"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:interactionListWiki",
    name: "interactionListWiki",
    displayName: "interactionListWiki",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "List interaction wiki notes, task candidates, and memory candidates.",
    capabilities: ["memory_read", "knowledge_read"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:ownerContextProcessRecordedMessages",
    name: "ownerContextProcessRecordedMessages",
    displayName: "ownerContextProcessRecordedMessages",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Process persisted message evidence into Owner Context candidates.",
    capabilities: ["message_read", "memory_write", "task_create"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:ownerContextListCandidates",
    name: "ownerContextListCandidates",
    displayName: "ownerContextListCandidates",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "List Owner Context task and memory candidates.",
    capabilities: ["memory_read", "knowledge_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:ownerContextGetEvidence",
    name: "ownerContextGetEvidence",
    displayName: "ownerContextGetEvidence",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Read original Owner Context evidence events by event id.",
    capabilities: ["message_read", "memory_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:ownerContextReviewCandidate",
    name: "ownerContextReviewCandidate",
    displayName: "ownerContextReviewCandidate",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Confirm or dismiss an Owner Context task or memory candidate.",
    capabilities: ["memory_write", "task_create"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:wechatLocalCheckNewMessages",
    name: "wechatLocalCheckNewMessages",
    displayName: "wechatLocalCheckNewMessages",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Check local WeChat unread/new messages.",
    capabilities: ["message_read"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:wechatLocalSessions",
    name: "wechatLocalSessions",
    displayName: "wechatLocalSessions",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "List local WeChat sessions.",
    capabilities: ["message_read"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:wechatLocalHistory",
    name: "wechatLocalHistory",
    displayName: "wechatLocalHistory",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Read local WeChat conversation history.",
    capabilities: ["message_read"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:wechatLocalSearch",
    name: "wechatLocalSearch",
    displayName: "wechatLocalSearch",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Search local WeChat messages.",
    capabilities: ["message_read"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:wechatCreateReplyDraft",
    name: "wechatCreateReplyDraft",
    displayName: "wechatCreateReplyDraft",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Create a WeChat reply draft without sending it.",
    capabilities: ["external_draft"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:workshopCreateOutboxDraft",
    name: "workshopCreateOutboxDraft",
    displayName: "workshopCreateOutboxDraft",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Create a workshop outbox draft for owner review or policy send.",
    capabilities: ["external_draft"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:douyinCheckAccount",
    name: "douyinCheckAccount",
    displayName: "douyinCheckAccount",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Check the local Douyin publisher adapter and login command plan.",
    capabilities: ["web_read"],
    risk: "low",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:videoRenderInvestmentBrief",
    name: "videoRenderInvestmentBrief",
    displayName: "videoRenderInvestmentBrief",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Render a local investment video with storyboard, voiceover, subtitles, and FFmpeg.",
    capabilities: ["file_write"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:videoGenerateInvestmentBrief",
    name: "videoGenerateInvestmentBrief",
    displayName: "videoGenerateInvestmentBrief",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Generate AI video background material for an investment brief; use local rendering for final cuts.",
    capabilities: ["file_write"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:douyinCreatePublishDraft",
    name: "douyinCreatePublishDraft",
    displayName: "douyinCreatePublishDraft",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Create a local Douyin publish draft for an already-rendered video.",
    capabilities: ["file_write"],
    risk: "medium",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:douyinPrepareUpload",
    name: "douyinPrepareUpload",
    displayName: "douyinPrepareUpload",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description: "Create an approval-ready Douyin upload preparation plan.",
    capabilities: ["external_draft"],
    risk: "high",
    runtimeScopes: ["workshop"],
  },
  {
    id: "workshop:douyinPublishApprovedDraft",
    name: "douyinPublishApprovedDraft",
    displayName: "douyinPublishApprovedDraft",
    source: "workshop_tools",
    serverName: "workshop-tools",
    description:
      "Create or execute a final Douyin publish command after owner approval.",
    capabilities: ["external_draft"],
    risk: "critical",
    runtimeScopes: ["workshop"],
  },
];

export const SKILL_TOOLS: AgentToolDescriptor[] = [
  {
    id: "skill:agent-browser",
    name: "agent-browser",
    displayName: "agent-browser",
    source: "skill",
    description: "Browser-oriented agent workflow skill.",
    capabilities: ["browser", "web_read"],
    risk: "medium",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
  {
    id: "skill:docx",
    name: "docx",
    displayName: "docx",
    source: "skill",
    description: "Create or inspect Word documents.",
    capabilities: ["document", "file_read", "file_write"],
    risk: "medium",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
  {
    id: "skill:frontend-design",
    name: "frontend-design",
    displayName: "frontend-design",
    source: "skill",
    description: "Frontend product and visual design guidance.",
    capabilities: ["unknown"],
    risk: "low",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
  {
    id: "skill:openzhiyu-api",
    name: "openzhiyu-api",
    displayName: "openzhiyu-api",
    source: "skill",
    description: "Zhiyu API implementation knowledge.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
  {
    id: "skill:openzhiyu-feature-guide",
    name: "openzhiyu-feature-guide",
    displayName: "openzhiyu-feature-guide",
    source: "skill",
    description: "Zhiyu feature implementation guide.",
    capabilities: ["knowledge_read"],
    risk: "low",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
  {
    id: "skill:openzhiyu-memory",
    name: "openzhiyu-memory",
    displayName: "openzhiyu-memory",
    source: "skill",
    description: "Zhiyu memory workflow guidance.",
    capabilities: ["memory_read", "memory_write"],
    risk: "medium",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
  {
    id: "skill:pdf",
    name: "pdf",
    displayName: "pdf",
    source: "skill",
    description: "Read or generate PDF files.",
    capabilities: ["document", "file_read", "file_write"],
    risk: "medium",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
  {
    id: "skill:pptx",
    name: "pptx",
    displayName: "pptx",
    source: "skill",
    description: "Create or inspect PowerPoint presentations.",
    capabilities: ["presentation", "file_read", "file_write"],
    risk: "medium",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
  {
    id: "skill:ui-ux-pro-max",
    name: "ui-ux-pro-max",
    displayName: "ui-ux-pro-max",
    source: "skill",
    description: "Advanced UI/UX product design guidance.",
    capabilities: ["unknown"],
    risk: "low",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
  {
    id: "skill:weather",
    name: "weather",
    displayName: "weather",
    source: "skill",
    description: "Weather lookup workflow guidance.",
    capabilities: ["web_read"],
    risk: "low",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
  {
    id: "skill:xlsx",
    name: "xlsx",
    displayName: "xlsx",
    source: "skill",
    description: "Create or inspect spreadsheets.",
    capabilities: ["spreadsheet", "file_read", "file_write"],
    risk: "medium",
    runtimeScopes: ALL_AGENT_RUNTIMES,
  },
];

export const USER_MCP_TOOLS: AgentToolDescriptor[] = [
  {
    id: "user-mcp:configured-tools",
    name: "configured-tools",
    displayName: "User MCP tools",
    source: "user_mcp",
    description:
      "Tools loaded from ~/.openzhiyu/mcp.json or OPENZHIYU_MCP_CONFIG_PATH.",
    capabilities: ["unknown"],
    risk: "high",
    runtimeScopes: ["chat", "loop"],
  },
];

export function listRegisteredAgentTools(): AgentToolDescriptor[] {
  return [
    ...CLAUDE_BUILTIN_TOOLS,
    ...BUSINESS_TOOLS,
    ...WORKSHOP_TOOLS,
    ...SKILL_TOOLS,
    ...USER_MCP_TOOLS,
  ];
}
